import type { Metadata } from "next";
import { FilterByGender, FilterBySpecies, FilterByStatus } from '@/app/components/filters'
import Logo from '@/app/components/ui/logo'
import Search from '@/app/components/search'

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className='bg-black'>
        <main>
        <Logo/>
        <section className='max-w-[1440px] mx-auto px-6 flex flex-col gap-4 justify-center items-center sm:grid sm:grid-cols-4'>
          <Search/>
          <FilterBySpecies/>
          <FilterByGender/>
          <FilterByStatus/>
        </section>
        {children}
      </main>
      </body>
    </html>
  );
}
